# Generated by Django 4.1.3 on 2022-11-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("caption", models.TextField()),
                ("topic", models.CharField(max_length=100)),
                ("photo", models.ImageField(upload_to="media/photo")),
                ("data", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
