# Generated by Django 4.1.3 on 2022-11-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=255)),
                ("about", models.CharField(max_length=255)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("Uzbek", "Uzbek"),
                            ("English", "English"),
                            ("Russian", "Russian"),
                        ],
                        max_length=50,
                    ),
                ),
                ("photo", models.ImageField(upload_to="media/books")),
                ("file", models.FileField(upload_to="File/books")),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
