# Generated by Django 4.1.3 on 2022-11-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_books"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="photo",
            field=models.ImageField(upload_to="photo"),
        ),
        migrations.AlterField(
            model_name="books",
            name="file",
            field=models.FileField(upload_to="books/file"),
        ),
        migrations.AlterField(
            model_name="books",
            name="photo",
            field=models.ImageField(upload_to="books"),
        ),
    ]
